### ISSUE TITLE
Heavorum health is rather high

### ISSUE THREAD

**Issue by boot2big** [TheOddlySeagull/Trin-Civil-Pack-V3-V4#6]
If you recall I helped to tweak every vehicle's health value to something more convention friendly (as I didn't have any pointers or tips to it before that), the general formula I use now is to take the vehicle's emptyMass, divide it by 10 and add or subtract a bit of health based on the vehicle's material strength, size, etc.
Sorry for not having told you how I do it

**Comment by boot2big** [comment]
[Vehicle_Health_and_Weapon_Damage_Conventions-3_2.txt](https://github.com/TheOddlySeagull/Trin-Civil-Pack-V3/files/14389695/Vehicle_Health_and_Weapon_Damage_Conventions-3_2.txt)
Methods based on this .txt

**Comment by TheOddlySeagull** [comment]
Fancy convention.
Lots of reading, so I won't read it now, but thanks
