### ISSUE TITLE
[1.12.2] Vehicles bouncing when on non-full height blocks

### ISSUE THREAD

**Issue by brisingraerowing** [TheOddlySeagull/Trin-Civil-Pack-V3-V4#8]
I've found that when using Fureniku's Roads non-full blocks, Trin vehicles will bounce up and down slightly. UNU vehicles don't bounce. Haven't tested other packs yet.

IV: 22.14.2
Trin Civ Pack: 3.21.1 (In game the version says 3.20.0).
Forge: 14.23.5.2860
MC: 1.12.2

**Comment by TheOddlySeagull** [comment]
Hello, I am not sure, but that mostly a MTS/Immersive Vehicles problem.
But I don't see why UNU won't have the problem…

**Comment by brisingraerowing** [comment]
The IV official vehicle pack also doesn't have the issue.

**Comment by brisingraerowing** [comment]
And now it seems to have stopped after restarting the game a couple times... This is weird.
